package de.takacick.onescaryblock.client.item.model;

import de.takacick.onescaryblock.OneScaryBlock;
import net.minecraft.client.model.*;
import net.minecraft.client.render.RenderLayer;
import net.minecraft.client.render.VertexConsumer;
import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;
import net.minecraft.client.util.math.MatrixStack;
import net.minecraft.entity.LivingEntity;
import net.minecraft.item.ItemStack;
import net.minecraft.util.Identifier;
import org.joml.Vector3f;

public class ScaryOneBlockItemModel extends ItemModel {

    public static final Identifier TEXTURE = new Identifier(OneScaryBlock.MOD_ID, "textures/entity/scary_one_block.png");
    private final ModelPart root;

    public ScaryOneBlockItemModel(ModelPart part) {
        super(RenderLayer::getEntityTranslucentCull);

        this.root = part;
    }

    @Override
    public void setAngles(LivingEntity livingEntity, ItemStack itemStack, long time, float tickDelta) {
        this.getPart().traverse().forEach(ModelPart::resetTransform);
        AnimationHelper.animate(this, IDLE, (long) ((time + tickDelta) / 20 * 1000), 1.0f, new Vector3f());
    }

    public void animateDying(LivingEntity livingEntity, ItemStack itemStack, long time, float tickDelta) {
        AnimationHelper.animate(this, DYING, (long) ((time + tickDelta) / 20 * 1000), 1.0f, new Vector3f());
    }

    @Override
    public void render(MatrixStack matrices, VertexConsumer vertices, int light, int overlay, float red, float green, float blue, float alpha) {
        this.getPart().render(matrices, vertices, light, overlay, red, green, blue, alpha);
    }

    @Override
    public ModelPart getPart() {
        return this.root;
    }

    @Override
    public Identifier getTexture(ItemStack itemStack) {
        return TEXTURE;
    }

    public static TexturedModelData getTexturedModelData() {
        ModelData modelData = new ModelData();
        ModelPartData modelPartData = modelData.getRoot();
        ModelPartData bone = modelPartData.addChild("bone", ModelPartBuilder.create().uv(0, 0).cuboid(-8.0F, -16.0F, -8.0F, 16.0F, 16.0F, 16.0F, new Dilation(0.0F)), ModelTransform.pivot(0.0F, 24.0F, 0.0F));

        ModelPartData eye_north = bone.addChild("eye_north", ModelPartBuilder.create().uv(1, 42).cuboid(-2.2F, -2.25F, -2.9493F, 4.0F, 5.5F, 5.8F, new Dilation(0.0F))
                .uv(-1, 33).cuboid(-3.9F, -1.35F, -2.8493F, 8.0F, 2.2F, 5.8F, new Dilation(0.0F))
                .uv(39, 54).cuboid(-3.4F, -2.15F, -2.9013F, 7.0F, 3.8F, 5.8F, new Dilation(0.0F)), ModelTransform.pivot(-0.6F, -5.75F, -5.3507F));

        ModelPartData eye_north_top_lid = eye_north.addChild("eye_north_top_lid", ModelPartBuilder.create().uv(0, 56).cuboid(-4.0F, -0.05F, -0.45F, 8.0F, 2.0F, 5.9F, new Dilation(0.01F)), ModelTransform.pivot(0.1F, -3.5F, -2.6993F));

        ModelPartData eye_north_bottom_lid = eye_north.addChild("eye_north_bottom_lid", ModelPartBuilder.create().uv(0, 56).cuboid(-4.0F, -1.95F, -0.35F, 8.0F, 2.0F, 5.9F, new Dilation(0.01F)), ModelTransform.pivot(0.1F, 3.6F, -2.7993F));

        ModelPartData eye_north_eye = eye_north.addChild("eye_north_eye", ModelPartBuilder.create().uv(30, 59).cuboid(-1.5F, -1.75F, 0.0F, 3.0F, 3.5F, 0.0F, new Dilation(0.0F)), ModelTransform.pivot(0.1F, -0.3F, -3.0493F));

        ModelPartData eye_south = bone.addChild("eye_south", ModelPartBuilder.create().uv(1, 42).cuboid(-2.2F, -2.25F, -2.9493F, 4.0F, 5.5F, 5.8F, new Dilation(0.0F))
                .uv(-1, 33).cuboid(-3.9F, -1.35F, -2.8493F, 8.0F, 2.2F, 5.8F, new Dilation(0.0F))
                .uv(39, 54).cuboid(-3.4F, -2.15F, -2.9013F, 7.0F, 3.8F, 5.8F, new Dilation(0.0F)), ModelTransform.of(-0.1F, -6.15F, 5.4493F, 3.1416F, 0.0F, 2.8449F));

        ModelPartData eye_south_top_lid = eye_south.addChild("eye_south_top_lid", ModelPartBuilder.create().uv(0, 56).cuboid(-4.0F, -0.05F, -0.45F, 8.0F, 2.0F, 5.9F, new Dilation(0.01F)), ModelTransform.pivot(0.1F, -3.5F, -2.6993F));

        ModelPartData eye_south_bottom_lid = eye_south.addChild("eye_south_bottom_lid", ModelPartBuilder.create().uv(0, 56).cuboid(-4.0F, -1.95F, -0.35F, 8.0F, 2.0F, 5.9F, new Dilation(0.01F)), ModelTransform.pivot(0.1F, 3.6F, -2.7993F));

        ModelPartData eye_south_eye = eye_south.addChild("eye_south_eye", ModelPartBuilder.create().uv(30, 59).cuboid(-1.5F, -1.75F, 0.0F, 3.0F, 3.5F, 0.0F, new Dilation(0.0F)), ModelTransform.pivot(0.1F, -0.3F, -3.0493F));

        ModelPartData eye_east = bone.addChild("eye_east", ModelPartBuilder.create().uv(1, 42).cuboid(-2.2F, -2.25F, -2.9493F, 4.0F, 5.5F, 5.8F, new Dilation(0.0F))
                .uv(-1, 33).cuboid(-3.9F, -1.35F, -2.8493F, 8.0F, 2.2F, 5.8F, new Dilation(0.0F))
                .uv(39, 54).cuboid(-3.4F, -2.15F, -2.9013F, 7.0F, 3.8F, 5.8F, new Dilation(0.0F)), ModelTransform.of(-5.3F, -6.85F, 0.0493F, -1.5708F, 1.4661F, -1.5708F));

        ModelPartData eye_east_top_lid = eye_east.addChild("eye_east_top_lid", ModelPartBuilder.create().uv(0, 56).cuboid(-4.0F, -0.05F, -0.45F, 8.0F, 2.0F, 5.9F, new Dilation(0.01F)), ModelTransform.pivot(0.1F, -3.5F, -2.6993F));

        ModelPartData eye_east_bottom_lid = eye_east.addChild("eye_east_bottom_lid", ModelPartBuilder.create().uv(0, 56).cuboid(-4.0F, -1.95F, -0.35F, 8.0F, 2.0F, 5.9F, new Dilation(0.01F)), ModelTransform.pivot(0.1F, 3.6F, -2.7993F));

        ModelPartData eye_east_eye = eye_east.addChild("eye_east_eye", ModelPartBuilder.create().uv(30, 59).cuboid(-1.5F, -1.75F, 0.0F, 3.0F, 3.5F, 0.0F, new Dilation(0.0F)), ModelTransform.pivot(0.1F, -0.3F, -3.0493F));

        ModelPartData eye_west = bone.addChild("eye_west", ModelPartBuilder.create().uv(1, 42).cuboid(-2.2F, -2.25F, -2.9493F, 4.0F, 5.5F, 5.8F, new Dilation(0.0F))
                .uv(-1, 33).cuboid(-3.9F, -1.35F, -2.8493F, 8.0F, 2.2F, 5.8F, new Dilation(0.0F))
                .uv(39, 54).cuboid(-3.4F, -2.15F, -2.9013F, 7.0F, 3.8F, 5.8F, new Dilation(0.0F)), ModelTransform.of(5.5F, -5.95F, 0.0493F, 1.5708F, -1.4661F, -1.5708F));

        ModelPartData eye_west_top_lid = eye_west.addChild("eye_west_top_lid", ModelPartBuilder.create().uv(0, 56).cuboid(-4.0F, -0.05F, -0.45F, 8.0F, 2.0F, 5.9F, new Dilation(0.01F)), ModelTransform.pivot(0.1F, -3.5F, -2.6993F));

        ModelPartData eye_west_bottom_lid = eye_west.addChild("eye_west_bottom_lid", ModelPartBuilder.create().uv(0, 56).cuboid(-4.0F, -1.95F, -0.35F, 8.0F, 2.0F, 5.9F, new Dilation(0.01F)), ModelTransform.pivot(0.1F, 3.6F, -2.7993F));

        ModelPartData eye_west_eye = eye_west.addChild("eye_west_eye", ModelPartBuilder.create().uv(30, 59).cuboid(-1.5F, -1.75F, 0.0F, 3.0F, 3.5F, 0.0F, new Dilation(0.0F)), ModelTransform.pivot(0.1F, -0.3F, -3.0493F));
        return TexturedModelData.of(modelData, 64, 64);
    }

    public static final Animation IDLE = Animation.Builder.create(2.75f).looping()
            .addBoneAnimation("eye_north_eye",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.125f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.20834334f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2916767f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.375f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4583433f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5834334f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.625f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6766666f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7083434f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7916766f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8343334f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.0416767f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.0834333f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.125f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1676667f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2083433f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.25f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2916767f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3433333f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.375f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4167667f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4583433f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5416767f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5834333f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.625f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.6766667f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.8343333f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.875f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9167667f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9583433f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.0416765f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.0834335f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.125f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.1676665f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.2083435f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.25f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.2916765f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.3433335f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.375f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.4167665f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.4583435f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5416765f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5834335f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.625f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("eye_north_top_lid",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(1.5416767f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.8343333f, AnimationHelper.createScalingVector(1f, 2.16f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9167667f, AnimationHelper.createScalingVector(1f, 2.2f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.2083435f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("eye_north_bottom_lid",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(1.5416767f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.8343333f, AnimationHelper.createScalingVector(1f, 1.57f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9167667f, AnimationHelper.createScalingVector(1f, 1.57f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.2083435f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("eye_south_top_lid",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(1.5416767f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.8343333f, AnimationHelper.createScalingVector(1f, 2.16f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9167667f, AnimationHelper.createScalingVector(1f, 2.2f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.2083435f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("eye_south_bottom_lid",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(1.5416767f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.8343333f, AnimationHelper.createScalingVector(1f, 1.57f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9167667f, AnimationHelper.createScalingVector(1f, 1.57f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.2083435f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("eye_south_eye",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.125f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.20834334f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2916767f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.375f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4583433f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5834334f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.625f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6766666f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7083434f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7916766f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8343334f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.0416767f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.0834333f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.125f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1676667f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2083433f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.25f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2916767f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3433333f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.375f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4167667f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4583433f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5416767f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5834333f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.625f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.6766667f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.8343333f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.875f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9167667f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9583433f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.0416765f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.0834335f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.125f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.1676665f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.2083435f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.25f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.2916765f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.3433335f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.375f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.4167665f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.4583435f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5416765f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5834335f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.625f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("eye_west_top_lid",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0.625f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9167666f, AnimationHelper.createScalingVector(1f, 2.16f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createScalingVector(1f, 2.2f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2916767f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("eye_west_bottom_lid",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0.625f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9167666f, AnimationHelper.createScalingVector(1f, 1.57f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createScalingVector(1f, 1.57f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2916767f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("eye_west_eye",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.125f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.20834334f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2916767f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.375f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4583433f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5834334f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.625f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6766666f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7083434f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7916766f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8343334f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.0416767f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.0834333f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.125f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1676667f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2083433f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.25f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2916767f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3433333f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.375f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4167667f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4583433f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5416767f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5834333f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.625f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.6766667f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.8343333f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.875f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9167667f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9583433f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.0416765f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.0834335f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.125f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.1676665f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.2083435f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.25f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.2916765f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.3433335f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.375f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.4167665f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.4583435f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5416765f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5834335f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.625f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("eye_east_top_lid",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(1.0834333f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.375f, AnimationHelper.createScalingVector(1f, 2.16f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4583433f, AnimationHelper.createScalingVector(1f, 2.2f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.75f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("eye_east_bottom_lid",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(1.0834333f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.375f, AnimationHelper.createScalingVector(1f, 1.57f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4583433f, AnimationHelper.createScalingVector(1f, 1.57f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.75f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("eye_east_eye",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.125f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.20834334f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2916767f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.375f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4583433f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5834334f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.625f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.6766666f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7083434f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7916766f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.8343334f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.0416767f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.0834333f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.125f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.1676667f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2083433f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.25f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2916767f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.3433333f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.375f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4167667f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.4583433f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5416767f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5834333f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.625f, AnimationHelper.createTranslationalVector(0.7f, 0.4f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.6766667f, AnimationHelper.createTranslationalVector(0.7f, 0.3f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.8343333f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.875f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9167667f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.9583433f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.0416765f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.0834335f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.125f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.1676665f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.2083435f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.25f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.2916765f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.3433335f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.375f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.4167665f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.4583435f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5416765f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5834335f, AnimationHelper.createTranslationalVector(-1f, -0.5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.625f, AnimationHelper.createTranslationalVector(-1f, -0.6f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR))).build();

    public static final Animation DYING = Animation.Builder.create(1.25f).looping()
            .addBoneAnimation("bone",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.20834334f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.2916767f, AnimationHelper.createRotationalVector(4.98f, -0.44f, 4.98f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.375f, AnimationHelper.createRotationalVector(4.98f, -0.44f, -4.98f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.4583433f, AnimationHelper.createRotationalVector(-4.98f, -0.44f, -4.98f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.5416766f, AnimationHelper.createRotationalVector(-4.98f, -0.44f, 4.98f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.625f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.7916766f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.875f, AnimationHelper.createRotationalVector(4.98f, -0.44f, 4.98f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.9583434f, AnimationHelper.createRotationalVector(4.98f, -0.44f, -4.98f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.0416767f, AnimationHelper.createRotationalVector(-4.98f, -0.44f, -4.98f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.125f, AnimationHelper.createRotationalVector(-4.98f, -0.44f, 4.98f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.2083433f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("bone",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.125f, AnimationHelper.createScalingVector(1.2f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.20834334f, AnimationHelper.createScalingVector(1.2f, 1f, 1.2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.2916767f, AnimationHelper.createScalingVector(1f, 1.2f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.375f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.4583433f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7083434f, AnimationHelper.createScalingVector(1.2f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.7916766f, AnimationHelper.createScalingVector(1.2f, 1f, 1.2f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.875f, AnimationHelper.createScalingVector(1f, 1.2f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.9583434f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.0416767f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR))).build();
}
