package de.takacick.elementalblock.registry;

import de.takacick.elementalblock.OneElementalBlock;
import de.takacick.elementalblock.registry.block.*;
import de.takacick.elementalblock.registry.block.fluid.LavaFluid;
import de.takacick.elementalblock.registry.block.fluid.TsunamicWaterFluid;
import de.takacick.elementalblock.registry.block.fluid.WaterFluid;
import de.takacick.elementalblock.registry.heart.LavaHeart;
import de.takacick.elementalblock.registry.item.*;
import de.takacick.utils.BionicUtils;
import de.takacick.utils.heart.Heart;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.minecraft.block.*;
import net.minecraft.block.enums.Instrument;
import net.minecraft.fluid.FlowableFluid;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.sound.SoundEvents;
import net.minecraft.util.Identifier;

public class ItemRegistry {
    public static final BlockSoundGroup LAVA_SOUND_GROUP = new BlockSoundGroup(1.0f, 1.0f, SoundEvents.BLOCK_STONE_BREAK, SoundEvents.BLOCK_STONE_STEP, SoundEvents.BLOCK_STONE_PLACE, SoundEvents.BLOCK_STONE_HIT, SoundEvents.BLOCK_STONE_FALL);
    public static final BlockSoundGroup WATER_SOUND_GROUP = new BlockSoundGroup(1.0f, 1.0f, SoundEvents.BLOCK_STONE_BREAK, SoundEvents.BLOCK_STONE_STEP, SoundEvents.BLOCK_STONE_PLACE, SoundEvents.BLOCK_STONE_HIT, SoundEvents.BLOCK_STONE_FALL);

    public static final Heart DIRT_HEART = BionicUtils.registerHeart(new Heart(new Identifier(OneElementalBlock.MOD_ID, "dirt"), true));
    public static final Heart LAVA_HEART = BionicUtils.registerHeart(new LavaHeart(new Identifier(OneElementalBlock.MOD_ID, "lava"), true, 9));

    public static final FlowableFluid WATER = new WaterFluid.Still();
    public static final FlowableFluid FLOWING_WATER = new WaterFluid.Flowing();
    public static final FluidBlock WATER_BLOCK = new CustomFluidBlock(WATER, FabricBlockSettings.copy(Blocks.WATER).strength(0.5f).sounds(WATER_SOUND_GROUP));
    public static final FlowableFluid TSUNAMIC_WATER = new TsunamicWaterFluid.Still();
    public static final FlowableFluid TSUNAMIC_FLOWING_WATER = new TsunamicWaterFluid.Flowing();
    public static final FluidBlock TSUNAMIC_WATER_BLOCK = new FluidBlock(TSUNAMIC_WATER, FabricBlockSettings.copy(Blocks.WATER).strength(0.5f).sounds(WATER_SOUND_GROUP));
    public static final FlowableFluid LAVA = new LavaFluid.Still();
    public static final FlowableFluid FLOWING_LAVA = new LavaFluid.Flowing();
    public static final FluidBlock LAVA_BLOCK = new CustomFluidBlock(LAVA, FabricBlockSettings.copy(Blocks.LAVA).strength(0.5f).sounds(LAVA_SOUND_GROUP));

    public static final ElementalBlock EARTH_ELEMENTAL_BLOCK = new EarthElementalBlock(AbstractBlock.Settings.create().mapColor(MapColor.DIRT_BROWN).strength(0.5f).sounds(BlockSoundGroup.GRAVEL));
    public static final Item EARTH_ELEMENTAL_BLOCK_ITEM = new BlockItem(EARTH_ELEMENTAL_BLOCK, new Item.Settings());
    public static final ElementalBlock AIR_ELEMENTAL_BLOCK = new AirElementalBlock(AbstractBlock.Settings.create().sounds(BlockSoundGroup.WOOL).noBlockBreakParticles().nonOpaque().strength(0.5f).blockVision((state, world, pos) -> false));
    public static final Item AIR_ELEMENTAL_BLOCK_ITEM = new BlockItem(AIR_ELEMENTAL_BLOCK, new Item.Settings());
    public static final ElementalBlock WATER_ELEMENTAL_BLOCK = new WaterElementalBlock(AbstractBlock.Settings.create().mapColor(MapColor.WATER_BLUE).noBlockBreakParticles().solidBlock((state, world, pos) -> false).ticksRandomly().strength(0.5f).sounds(WATER_SOUND_GROUP));
    public static final Item WATER_ELEMENTAL_BLOCK_ITEM = new BlockItem(WATER_ELEMENTAL_BLOCK, new Item.Settings());
    public static final ElementalBlock FIRE_ELEMENTAL_BLOCK = new FireElementalBlock(AbstractBlock.Settings.create().mapColor(MapColor.DARK_RED).instrument(Instrument.BASEDRUM).luminance(state -> 3).strength(0.5f).postProcess(Blocks::always).emissiveLighting(Blocks::always));
    public static final Item FIRE_ELEMENTAL_BLOCK_ITEM = new BlockItem(FIRE_ELEMENTAL_BLOCK, new Item.Settings());
    public static final Item TERRA_DRILL = new TerraDrill(new Item.Settings().maxCount(1));
    public static final Item WORM = new Worm(new Item.Settings());
    public static final Item DIRT_HEART_ITEM = new DirtHeart(new Item.Settings());
    public static final Item TREE = new Tree(new Item.Settings().maxCount(1));
    public static final Item COBBLE_GAUNTLET = new CobbleGauntlet(new Item.Settings().maxCount(1));
    public static final Block CLOUD_BLOCK = new CloudBlock(AbstractBlock.Settings.create().sounds(BlockSoundGroup.WOOL).nonOpaque().strength(0.2F).blockVision((state, world, pos) -> false));
    public static final Item CLOUD_BLOCK_ITEM = new CloudBlockItem(CLOUD_BLOCK, new Item.Settings());
    public static final Block CLOUD_LOG = new CloudPillarBlock(AbstractBlock.Settings.create().mapColor(MapColor.WHITE).nonOpaque().strength(2.0f).sounds(BlockSoundGroup.WOOD).blockVision((state, world, pos) -> false));
    public static final Item CLOUD_LOG_ITEM = new CloudBlockItem(CLOUD_LOG, new Item.Settings());
    public static final Block CLOUD_PLANKS = new Block(AbstractBlock.Settings.create().mapColor(MapColor.WHITE).strength(2.0f, 3.0f).sounds(BlockSoundGroup.WOOD));
    public static final Item CLOUD_PLANKS_ITEM = new CloudBlockItem(CLOUD_PLANKS, new Item.Settings());
    public static final Item MAGIC_CLOUD_BUDDY = new MagicCloudBuddy(new Item.Settings());
    public static final Item WHISPERWIND_BOW = new WhisperwindBow(new Item.Settings().maxCount(1));
    public static final Item WATER_BLOCK_ITEM = new BlockItem(WATER_BLOCK, new Item.Settings());
    public static final Item WATER_ARMOR_VESSEL = new WaterArmorVessel(new Item.Settings().maxCount(1));
    public static final Item TSUNAMIC_TRIDENT = new TsunamicTrident(new Item.Settings().maxCount(1));
    public static final Block MAGMA_LOG = new PillarBlock(AbstractBlock.Settings.create().mapColor(MapColor.DARK_RED).strength(2.0f).luminance(state -> 3).postProcess((state, world, pos) -> true).emissiveLighting((state, world, pos) -> true).sounds(BlockSoundGroup.WOOD));
    public static final Item MAGMA_LOG_ITEM = new BlockItem(MAGMA_LOG, new Item.Settings().fireproof());
    public static final Item LAVA_BLOCK_ITEM = new BlockItem(LAVA_BLOCK, new Item.Settings().fireproof());
    public static final Block MAGMA_PLANKS = new Block(AbstractBlock.Settings.create().mapColor(MapColor.DARK_RED).strength(2.0f, 3.0f).luminance(state -> 3).postProcess((state, world, pos) -> true).emissiveLighting((state, world, pos) -> true).sounds(BlockSoundGroup.WOOD));
    public static final Item MAGMA_PLANKS_ITEM = new BlockItem(MAGMA_PLANKS, new Item.Settings().fireproof());
    public static final Block MAGMA_GRASS_BLOCK = new MagmaGrassBlock(AbstractBlock.Settings.create().mapColor(MapColor.DARK_RED).ticksRandomly().strength(0.6f).sounds(BlockSoundGroup.GRASS).luminance(state -> 3).postProcess((state, world, pos) -> true).emissiveLighting((state, world, pos) -> true));
    public static final Item MAGMA_GRASS_BLOCK_ITEM = new BlockItem(MAGMA_GRASS_BLOCK, new Item.Settings().fireproof());
    public static final Item MAGIC_LAVA_SCRIPTURE = new MagicLavaScripture(new Item.Settings().fireproof().maxDamage(3));

    public static void register() {
        Registry.register(Registries.BLOCK, new Identifier(OneElementalBlock.MOD_ID, "earth_elemental_block"), EARTH_ELEMENTAL_BLOCK);
        Registry.register(Registries.ITEM, new Identifier(OneElementalBlock.MOD_ID, "earth_elemental_block"), EARTH_ELEMENTAL_BLOCK_ITEM);
        Registry.register(Registries.BLOCK, new Identifier(OneElementalBlock.MOD_ID, "air_elemental_block"), AIR_ELEMENTAL_BLOCK);
        Registry.register(Registries.ITEM, new Identifier(OneElementalBlock.MOD_ID, "air_elemental_block"), AIR_ELEMENTAL_BLOCK_ITEM);
        Registry.register(Registries.BLOCK, new Identifier(OneElementalBlock.MOD_ID, "water_elemental_block"), WATER_ELEMENTAL_BLOCK);
        Registry.register(Registries.ITEM, new Identifier(OneElementalBlock.MOD_ID, "water_elemental_block"), WATER_ELEMENTAL_BLOCK_ITEM);
        Registry.register(Registries.BLOCK, new Identifier(OneElementalBlock.MOD_ID, "fire_elemental_block"), FIRE_ELEMENTAL_BLOCK);
        Registry.register(Registries.ITEM, new Identifier(OneElementalBlock.MOD_ID, "fire_elemental_block"), FIRE_ELEMENTAL_BLOCK_ITEM);
        Registry.register(Registries.ITEM, new Identifier(OneElementalBlock.MOD_ID, "terra_drill"), TERRA_DRILL);
        Registry.register(Registries.ITEM, new Identifier(OneElementalBlock.MOD_ID, "worm"), WORM);
        Registry.register(Registries.ITEM, new Identifier(OneElementalBlock.MOD_ID, "dirt_heart"), DIRT_HEART_ITEM);
        Registry.register(Registries.ITEM, new Identifier(OneElementalBlock.MOD_ID, "tree"), TREE);
        Registry.register(Registries.ITEM, new Identifier(OneElementalBlock.MOD_ID, "cobble_gauntlet"), COBBLE_GAUNTLET);
        Registry.register(Registries.BLOCK, new Identifier(OneElementalBlock.MOD_ID, "cloud_block"), CLOUD_BLOCK);
        Registry.register(Registries.ITEM, new Identifier(OneElementalBlock.MOD_ID, "cloud_block"), CLOUD_BLOCK_ITEM);
        Registry.register(Registries.BLOCK, new Identifier(OneElementalBlock.MOD_ID, "cloud_log"), CLOUD_LOG);
        Registry.register(Registries.ITEM, new Identifier(OneElementalBlock.MOD_ID, "cloud_log"), CLOUD_LOG_ITEM);
        Registry.register(Registries.BLOCK, new Identifier(OneElementalBlock.MOD_ID, "cloud_planks"), CLOUD_PLANKS);
        Registry.register(Registries.ITEM, new Identifier(OneElementalBlock.MOD_ID, "cloud_planks"), CLOUD_PLANKS_ITEM);
        Registry.register(Registries.ITEM, new Identifier(OneElementalBlock.MOD_ID, "magic_cloud_buddy"), MAGIC_CLOUD_BUDDY);
        Registry.register(Registries.ITEM, new Identifier(OneElementalBlock.MOD_ID, "whisperwind_bow"), WHISPERWIND_BOW);
        Registry.register(Registries.BLOCK, new Identifier(OneElementalBlock.MOD_ID, "water_block"), WATER_BLOCK);
        Registry.register(Registries.ITEM, new Identifier(OneElementalBlock.MOD_ID, "water_block"), WATER_BLOCK_ITEM);
        Registry.register(Registries.FLUID, new Identifier(OneElementalBlock.MOD_ID, "tsunamic_water"), TSUNAMIC_WATER);
        Registry.register(Registries.FLUID, new Identifier(OneElementalBlock.MOD_ID, "tsunamic_flowing_water"), TSUNAMIC_FLOWING_WATER);
        Registry.register(Registries.BLOCK, new Identifier(OneElementalBlock.MOD_ID, "tsunamic_water_block"), TSUNAMIC_WATER_BLOCK);
        Registry.register(Registries.FLUID, new Identifier(OneElementalBlock.MOD_ID, "water"), WATER);
        Registry.register(Registries.FLUID, new Identifier(OneElementalBlock.MOD_ID, "flowing_water"), FLOWING_WATER);
        Registry.register(Registries.ITEM, new Identifier(OneElementalBlock.MOD_ID, "water_armor_vessel"), WATER_ARMOR_VESSEL);
        Registry.register(Registries.ITEM, new Identifier(OneElementalBlock.MOD_ID, "tsunamic_trident"), TSUNAMIC_TRIDENT);
        Registry.register(Registries.BLOCK, new Identifier(OneElementalBlock.MOD_ID, "lava_block"), LAVA_BLOCK);
        Registry.register(Registries.ITEM, new Identifier(OneElementalBlock.MOD_ID, "lava_block"), LAVA_BLOCK_ITEM);
        Registry.register(Registries.FLUID, new Identifier(OneElementalBlock.MOD_ID, "lava"), LAVA);
        Registry.register(Registries.FLUID, new Identifier(OneElementalBlock.MOD_ID, "flowing_lava"), FLOWING_LAVA);
        Registry.register(Registries.BLOCK, new Identifier(OneElementalBlock.MOD_ID, "magma_log"), MAGMA_LOG);
        Registry.register(Registries.ITEM, new Identifier(OneElementalBlock.MOD_ID, "magma_log"), MAGMA_LOG_ITEM);
        Registry.register(Registries.BLOCK, new Identifier(OneElementalBlock.MOD_ID, "magma_planks"), MAGMA_PLANKS);
        Registry.register(Registries.ITEM, new Identifier(OneElementalBlock.MOD_ID, "magma_planks"), MAGMA_PLANKS_ITEM);
        Registry.register(Registries.BLOCK, new Identifier(OneElementalBlock.MOD_ID, "magma_grass_block"), MAGMA_GRASS_BLOCK);
        Registry.register(Registries.ITEM, new Identifier(OneElementalBlock.MOD_ID, "magma_grass_block"), MAGMA_GRASS_BLOCK_ITEM);
        Registry.register(Registries.ITEM, new Identifier(OneElementalBlock.MOD_ID, "magic_lava_scripture"), MAGIC_LAVA_SCRIPTURE);
    }
}